version: '3.0'
volumes:
  data:
  extensions:
  logs:
  postgresql:
  postgresql_data:
services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: $SONAR_JDBC_USERNAME
      SONAR_JDBC_PASSWORD: $SONAR_JDBC_PASSWORD
    volumes:
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
    ports:
      - "9050:9000"
    env_file:
      - .env
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U sonar"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWD
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env



