- id: '1673320887191'
  alias: Bed time
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.light_2
      state: 'off'
    - condition: state
      entity_id: switch.plug_2_socket_1
      state: 'off'
    - condition: state
      entity_id: switch.plug_1_socket_1
      state: 'off'
    - condition: state
      entity_id: light.light_2
      state: 'off'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bed_time
    metadata: {}
  mode: single
- id: '1673406720098'
  alias: Morning heat
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: state
    entity_id: climate.downstairs
    attribute: current_temperature
    state: '66'
  action:
  - service: climate.set_temperature
    data:
      temperature: 72
      hvac_mode: heat_cool
    target:
      entity_id: climate.downstairs
  mode: single
