# Panel Configs
## Add Container User Interface to Naviagtion menu
panel_iframe:
  portainer:
    title: 'Portainer'
    url: 'http://192.168.1.186:9000/#/containers'
    icon: mdi:docker
    require_admin: true

# Loads default set of integrations. Do not remove.
default_config:

#PowerCalc
powercalc:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# System Monitor
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: disk_free
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature

# logger
logger:
  default: warning
  logs:
    custom_components.powercalc: debug

# MQTT Discovery
# mqtt_discoverystream:
#   base_topic: test_HA
#   publish_attributes: false
#   publish_timestamps: true
#   publish_discovery: true
#   include:
#     entities:
#       - sensor.owm_hourly_humidity
#       - sensor.jellyfin_cloud
#       - light.wled_esp
#   exclude:
#     entities:
#       - sensor.plug_xiaomi_1_electrical_measurement

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
