- id: '1673320752895'
  name: Bed time
  entities:
    light.coffee_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      friendly_name: Coffe room lamp
      supported_features: 0
      state: 'off'
    light.light_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      friendly_name: Lamp
      supported_features: 0
      state: 'off'
    switch.plug_2_socket_1:
      device_class: outlet
      friendly_name: LED sign
      state: 'off'
    switch.plug_1_socket_1:
      device_class: outlet
      friendly_name: Living room lamp
      state: 'off'
    climate.downstairs:
      hvac_modes:
      - 'off'
      - cool
      - heat_cool
      - heat
      min_temp: 50
      max_temp: 90
      fan_modes:
      - 'on'
      - 'off'
      preset_modes:
      - none
      - eco
      current_temperature: 70
      temperature: 66
      target_temp_high:
      target_temp_low:
      fan_mode: 'off'
      hvac_action: idle
      preset_mode: none
      friendly_name: Downstairs
      supported_features: 27
      state: heat
  icon: mdi:bed
  metadata:
    light.coffee_room:
      entity_only: true
    light.light_2:
      entity_only: true
    switch.plug_2_socket_1:
      entity_only: true
    switch.plug_1_socket_1:
      entity_only: true
    climate.downstairs:
      entity_only: true
