version: "3"
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: $HOSTNAME
    domainname: $DOMAIN_NAME
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 22/tcp
      - 80:80/tcp
      - 443:443/tcp
      - 5335:5335/tcp # unbound access on local server
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: $PASSWORD # Set your password or remove for a random one
      FTLCONF_LOCAL_IPV4: $FTLCONF_LOCAL_IPV4
      WEBTHEME: $WEBTHEME
      REV_SERVER: $REV_SERVER
      REV_SERVER_TARGET: $REV_SERVER_TARGET
      REV_SERVER_DOMAIN: $REV_SERVER_DOMAIN
      REV_SERVER_CIDR: $REV_SERVER_CIDR
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      DNSMASQ_LISTENING: single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
    env_file:
      - .env
