version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required for DHCP server
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: $PASSWORD # Set your password or remove for a random one
      SERVERIP: $SERVER_IP # Set your server IP
      DHCP_ACTIVE: 'true' # Enable DHCP server
      DHCP_START: '192.168.0.100' # Set DHCP range start
      DHCP_END: '192.168.0.250' # Set DHCP range end
      DHCP_ROUTER: '192.168.0.1' # Set your router IP
      DHCP_LEASETIME: '24' # Lease time in hours
      PIHOLE_DOMAIN: 'lan' # Local domain name
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
