version: '3.0'
volumes:
  config:
services:
  heimdall:
      image: lscr.io/linuxserver/heimdall:latest
      container_name: heimdall
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=US/New-York
      volumes:
        - config:/config 
      ports:
        - 80:80
        - 444:443
      restart: unless-stopped