version: '3.8'

services:
  semaphore:
    build: .
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      SEMAPHORE_ADMIN_USER_LOGIN: $SEMAPHORE_ADMIN_USER_LOGIN
      SEMAPHORE_ADMIN_USER_NAME: $SEMAPHORE_ADMIN_USER_NAME
      SEMAPHORE_ADMIN_USER_EMAIL: $SEMAPHORE_ADMIN_USER_EMAIL
      SEMAPHORE_ADMIN_USER_PASSWD: $SEMAPHORE_ADMIN_USER_PASSWD
    volumes:
      - ./config:/opt/semaphore/config
      - semaphore_data:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

volumes:
  semaphore_data:
